### PR TITLE
feat: Charging status

### LINKED ISSUE #39: Charging status
Read the battery voltage and display the battery percentage icon after splash.

### PR DESCRIPTION
**Pull request by kienvo**
Resolves #39.

## Summary by Sourcery

Implement a charging status feature that includes battery level detection and display, along with a new font rendering capability for text display on the device.

New Features:
- Introduce a charging status feature that detects and displays the battery charging state and percentage on the device.

Enhancements:
- Add a new font rendering capability to display text on the device's framebuffer using a 5x7 font.

### CODE REVIEW

**Comment by froscon2024** [comment]
Why did you add the coffee cup again? Yes, it was there before in the closed source firmware, but is the coffee cup something that should be there? Did you liked the design of the coffee cup?
I would prefer something else next to the battery symbol so that you can see a difference between the open and the closed firmware when they are both in this state. Maybe write "FOSSASIA" and the firmware version there instead of a useless coffee cup. Or at least only the firmware version next to the battery symbol.

Also one thing i did not liked in the closed source firmware was that it was not possible to charge the badge and still use it. I had either the tag-info without charger attached or coffee cup when charger attached.
Adding the option to charge while still displaying the information would be the first benefit of the FOSS firmware compared to the closed source one.

**Comment by kienvo** [comment]
The coffee cup was added because of my laziness. I had no idea instead of just made it like the closed firmware. Now removed.

Placing the firmware version next to the battery symbol is a good idea. I've just added an animation that displays "FOSSASIA" -> "Badge Magic" -> version. The version number will automated in #53.
badgemagic charging preview


My badge comes with closed firmware that can be used while charging, by pressing the KEY2. Seem like your badge has a different firmware.

**Comment by fcartegnie** [comment]
> The coffee cup was added because of my laziness. I had no idea instead of just made it like the closed firmware. Now removed.

Can't we just make simple things ?
We don't need to write version nor advertise fossasia everywhere.

**Comment by froscon2024** [comment]
Having the firmware version somewhere visible for a normal user without the need of additional hardware to read out would be beneficial. In general people always have devices these days that report a firmware version.
The closed source OEM firmware just had a single version and there was no changes planned. But now there are versions and probably feature addons and functionality differences between the versions. Letting the people know what version is installed is nice.

**Pull request merged**
